name: flood_tool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - gdal
  - pip:
      - distance-map
      - geopandas
      - pillow
      - planetary-computer
      - pystac-client
      - rasterio
      - rioxarray
      - scikit-image
      - shapely
      - torch
      - tqdm